CleanMvc.WebUI/Controllers/CategoriasController.cs
using CleanMvc.Application.DTOs;
using CleanMvc.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CleanMvc.WebUI.Controllers
{
    [Authorize]//significa que todos metodos só podem ser acessados por usuarios autenticados
    public class CategoriasController : Controller
    {
        private readonly ICategoriaService _categoriaService;
        public CategoriasController(ICategoriaService categoriaService)//traz a injecao de dependencia 
        {
               _categoriaService = categoriaService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var categorias = await _categoriaService.GetCategorias();
            return View(categorias);
        }

        [HttpGet]
        public IActionResult Criar() 
        { 
           return View();
        }

        [HttpPost]
        public async Task<IActionResult> Criar(CategoriaDTO categoriaDTO)
        {
            if(ModelState.IsValid) //verificacao feita pelo data anatotation da classe DTO
            {
              await _categoriaService.Add(categoriaDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(categoriaDTO);
        }

        [HttpGet]
        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null) return NotFound();
            var categoriaDto = await _categoriaService.GetById(id);
            if(categoriaDto == null) return NotFound();

             return View(categoriaDto); 
        }

        [HttpPost]
        public async Task<ActionResult> Editar(CategoriaDTO categoriaDTO)
        {
            if (ModelState.IsValid) //verificacao feita pelo data anatotation da classe DTO
            {
                try
                {
                    await _categoriaService.Update(categoriaDTO);
                }
                catch (Exception ex)
                {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(categoriaDTO);
        }

        [HttpGet]
        public async Task<IActionResult> Deletar(int? id)
        {
            if (id == null) return NotFound();

            var categoriaDTO = await _categoriaService.GetById(id);
            if(categoriaDTO == null) return NotFound(); 
            return View(categoriaDTO);
        }

        [HttpPost,ActionName("Deletar")]//cria outro com nome para não ter dois metodos com mesmo nome e não dar conflito
        public async Task<ActionResult> ConfirmarDelecao(int id)
        {
            await _categoriaService.Remove(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detalhes(int? id)
        {
            if (id == null) return NotFound();

            var categoriaDTO = await _categoriaService.GetById(id);

            if( categoriaDTO == null) return NotFound(); 
            return View(categoriaDTO);
        }
    }
}

CleanMvc.WebUI/Controllers/ProdutosController.cs
using CleanMvc.Application.DTOs;
using CleanMvc.Application.Interfaces;
using CleanMvc.Application.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace CleanMvc.WebUI.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly IProdutotService _produtotService;
        private readonly ICategoriaService _categoriaService;
        private readonly IWebHostEnvironment _environment;

        public ProdutosController(IProdutotService produtotService, ICategoriaService categoriaService, IWebHostEnvironment webHostEnvironment)
        {
            _produtotService = produtotService;
            _categoriaService = categoriaService;
            _environment = webHostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var produtos = await _produtotService.GetProdutos();
            return View(produtos);
        }

        [HttpGet]
        public async Task<IActionResult> Criar()//passa lista de categorias para dropboxlist
        {
            ViewBag.CategoriaId =
            new SelectList(await _categoriaService.GetCategorias(), "Id", "Nome");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Criar(ProdutoDTO produtoDTO)
        {
            if (ModelState.IsValid)
            {
                await _produtotService.Add(produtoDTO);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.CategoriaId =
                            new SelectList(await _categoriaService.GetCategorias(), "Id", "Nome");
            }
            return View(produtoDTO);
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null) return NotFound();
            var productDto = await _produtotService.GetById(id);

            if (productDto == null) return NotFound();

            var categorias = await _categoriaService.GetCategorias();
            ViewBag.CategoriaId = new SelectList(categorias, "Id", "Nome", productDto.CategoriaId);

            return View(productDto);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(ProdutoDTO produtoDTO)
        {
            if (ModelState.IsValid)
            {
                await _produtotService.Update(produtoDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(produtoDTO);
        }


        [Authorize(Roles ="Admin")]//somente usuarios autenticados Admin
        [HttpGet]
        public async Task<IActionResult> Deletar(int? id)
        {
            if (id == null)
                return NotFound();

            var produtoDto = await _produtotService.GetById(id);

            if (produtoDto == null) return NotFound();

            return View(produtoDto);
        }

        [HttpPost(), ActionName("Deletar")]
        public async Task<IActionResult> ConfirmarDelecao(int id)
        {
            await _produtotService.Remove(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detalhes(int? id)
        {
            if (id == null) return NotFound();
            var produtoDto = await _produtotService.GetProdutoCategoria(id);

            if (produtoDto == null) return NotFound();
            var wwwroot = _environment.WebRootPath;
            var image = Path.Combine(wwwroot, "images\\" + produtoDto.Imagem);
            var exists = System.IO.File.Exists(image);
            ViewBag.ImageExist = exists;

            return View(produtoDto);
        }

       
    }
}

CleanMvc.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catalogo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleanMvc.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Catalogo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacidade">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @await Html.PartialAsync("_LoginPartial")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Estudo de Clean Code - Tiago Portela <a asp-area="" asp-controller="Home" asp-action="Privacidade">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>